import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const font = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-[#EFEEF3]`}>{children}</body>
    </html>
  );
}
